import type { Metadata } from "next";
import { Providers } from "./providers";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Think Easy App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
